version: '3.8'

services:
  # Backend service (Python Flask API)
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: multigenqa-backend
    ports:
      - "5001:5001"
    environment:
      # You need to set these environment variables
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    env_file:
      - backend/.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend service (React/TypeScript with nginx)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: multigenqa-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

# Optional: Create a custom network for the services
networks:
  default:
    name: multigenqa-network 